### ISSUE TITLE
Forked and tests fail

### ISSUE THREAD

**Issue by ghost** [gkushang/cucumber-parallel#12]
Hey,

I forked the repo and wanted to check my set up so I'm running the tests.

`pretest` run is good.
`test` fails with the following:

```
AssertionError: Scenarios are missing in the report: expected 14 to equal 8
    at assertJsonContents (C:\Dev\cucumber-parallel\test\features\assert\report.js:24:45)
    at Timeout.assert [as _onTimeout] (C:\Dev\cucumber-parallel\test\features\assert\report.js:39:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

[cucumber_report.zip](https://github.com/gkushang/cucumber-parallel/files/774108/cucumber_report.zip)

I've attached a zip of the json file with what appear to be duplicates runs during the parallel scenarios run.

I'm going to look into whats going on but thought I'd flag this first.

**Comment by gkushang** [comment]
It seems like the user `ghost` really does not exist. We are closing the issue. Feel free to provide any feedback in the future. 

Thanks!
